import type { Car } from './types';

/** Mock rental fleet across the airports and cities this site covers. No live inventory. */
export const cars: Car[] = [
  {
    id: "bkk-economy-yaris",
    category: "Economy",
    model: "Toyota Yaris or similar",
    transmission: "Automatic",
    seats: 5,
    supplier: "Siam Rent-a-Car",
    location: "Bangkok Suvarnabhumi Airport (BKK)",
    pricePerDay: "$18",
  },
  {
    id: "bkk-suv-fortuner",
    category: "SUV",
    model: "Toyota Fortuner or similar",
    transmission: "Automatic",
    seats: 7,
    supplier: "Siam Rent-a-Car",
    location: "Bangkok Suvarnabhumi Airport (BKK)",
    pricePerDay: "$42",
  },
  {
    id: "hkt-compact-city",
    category: "Compact",
    model: "Honda City or similar",
    transmission: "Automatic",
    seats: 5,
    supplier: "Andaman Wheels",
    location: "Phuket International Airport (HKT)",
    pricePerDay: "$21",
  },
  {
    id: "hkt-convertible-mx5",
    category: "Convertible",
    model: "Mazda MX-5 or similar",
    transmission: "Manual",
    seats: 2,
    supplier: "Andaman Wheels",
    location: "Phuket International Airport (HKT)",
    pricePerDay: "$65",
  },
  {
    id: "cnx-economy-city",
    category: "Economy",
    model: "Honda City or similar",
    transmission: "Automatic",
    seats: 5,
    supplier: "Northern Thai Auto",
    location: "Chiang Mai International Airport (CNX)",
    pricePerDay: "$16",
  },
  {
    id: "cnx-van-hiace",
    category: "Van",
    model: "Toyota Hiace or similar",
    transmission: "Automatic",
    seats: 10,
    supplier: "Northern Thai Auto",
    location: "Chiang Mai International Airport (CNX)",
    pricePerDay: "$58",
  },
  {
    id: "usm-compact-jazz",
    category: "Compact",
    model: "Honda Jazz or similar",
    transmission: "Automatic",
    seats: 5,
    supplier: "Island Rentals Samui",
    location: "Koh Samui Airport (USM)",
    pricePerDay: "$24",
  },
  {
    id: "kbv-suv-cx5",
    category: "SUV",
    model: "Mazda CX-5 or similar",
    transmission: "Automatic",
    seats: 5,
    supplier: "Krabi Coastal Cars",
    location: "Krabi Airport (KBV)",
    pricePerDay: "$38",
  },
];
