import type { Car } from './types';

/*
 * Mock rental fleet across the airports and cities this site covers. No live
 * inventory, and every rate, rating and review count is fixed sample data
 * kept internally consistent (each supplier always carries the same rating,
 * each total exceeds its per-day rate) so the results page reads like a real
 * one. The same model appears at more than one pick-up point, the way a real
 * fleet does.
 *
 * The photos are real: openly-licensed (CC BY-SA 4.0) shots from Wikimedia
 * Commons, resized for the web. Each one carries the credit its license
 * requires; the full list also appears at the foot of /cars.
 */
export const cars: Car[] = [
  {
    id: 'bkk-economy-yaris',
    category: 'Economy',
    model: 'Toyota Yaris or similar',
    transmission: 'Automatic',
    seats: 5,
    fuel: 'Petrol',
    unlimitedMileage: true,
    allWheelDrive: false,
    supplier: 'Siam Rent-a-Car',
    supplierRatingPercent: 79,
    supplierReviewCount: 24,
    locationType: 'Airport',
    freeShuttle: true,
    city: 'Bangkok',
    distanceMiles: 18.6,
    address: 'Suvarnabhumi Airport, Level 2 Arrivals',
    location: 'Bangkok Suvarnabhumi Airport (BKK)',
    onlineCheckIn: true,
    payNow: true,
    refundable: true,
    pricePerDay: '$18',
    totalPrice: '$54',
    image: '/Content/cars/toyota-yaris.jpg',
    imageAlt: 'Toyota Yaris hatchback',
    photoCredit: 'Nikolai Bulykin, CC BY-SA 4.0, via Wikimedia Commons',
  },
  {
    id: 'bkk-suv-fortuner',
    category: 'SUV',
    model: 'Toyota Fortuner or similar',
    transmission: 'Automatic',
    seats: 7,
    fuel: 'Diesel',
    unlimitedMileage: true,
    allWheelDrive: true,
    supplier: 'Siam Rent-a-Car',
    supplierRatingPercent: 79,
    supplierReviewCount: 24,
    locationType: 'Airport',
    freeShuttle: true,
    city: 'Bangkok',
    distanceMiles: 18.6,
    address: 'Suvarnabhumi Airport, Level 2 Arrivals',
    location: 'Bangkok Suvarnabhumi Airport (BKK)',
    onlineCheckIn: true,
    payNow: true,
    refundable: true,
    pricePerDay: '$42',
    totalPrice: '$126',
    image: '/Content/cars/toyota-fortuner.jpg',
    imageAlt: 'Toyota Fortuner SUV',
    photoCredit: 'Matti Blume, CC BY-SA 4.0, via Wikimedia Commons',
  },
  {
    id: 'bkk-compact-city-sukhumvit',
    category: 'Compact',
    model: 'Honda City or similar',
    transmission: 'Automatic',
    seats: 5,
    fuel: 'Petrol',
    unlimitedMileage: true,
    allWheelDrive: false,
    supplier: 'Bangkok City Drive',
    supplierRatingPercent: 58,
    supplierReviewCount: 3,
    locationType: 'Non-airport',
    freeShuttle: false,
    city: 'Bangkok',
    distanceMiles: 1.4,
    address: '218 Sukhumvit Road, Khlong Toei',
    location: 'Bangkok city centre',
    onlineCheckIn: false,
    payNow: false,
    refundable: true,
    pricePerDay: '$23',
    totalPrice: '$69',
    wasPrice: '$78',
    image: '/Content/cars/honda-city.jpg',
    imageAlt: 'Honda City sedan',
    photoCredit: 'Ethan Llamas, CC BY-SA 4.0, via Wikimedia Commons',
  },
  {
    id: 'bkk-van-hiace-city',
    category: 'Van',
    model: 'Toyota Hiace or similar',
    transmission: 'Automatic',
    seats: 10,
    fuel: 'Diesel',
    unlimitedMileage: false,
    allWheelDrive: false,
    supplier: 'Bangkok City Drive',
    supplierRatingPercent: 58,
    supplierReviewCount: 3,
    locationType: 'Non-airport',
    freeShuttle: false,
    city: 'Bangkok',
    distanceMiles: 1.4,
    address: '218 Sukhumvit Road, Khlong Toei',
    location: 'Bangkok city centre',
    onlineCheckIn: false,
    payNow: false,
    refundable: true,
    pricePerDay: '$62',
    totalPrice: '$186',
    image: '/Content/cars/toyota-hiace.jpg',
    imageAlt: 'Toyota Hiace passenger van',
    photoCredit: 'Ethan Llamas, CC BY-SA 4.0, via Wikimedia Commons',
  },
  {
    id: 'hkt-compact-city',
    category: 'Compact',
    model: 'Honda City or similar',
    transmission: 'Automatic',
    seats: 5,
    fuel: 'Petrol',
    unlimitedMileage: true,
    allWheelDrive: false,
    supplier: 'Andaman Wheels',
    supplierRatingPercent: 84,
    supplierReviewCount: 11,
    locationType: 'Airport',
    freeShuttle: true,
    city: 'Phuket',
    distanceMiles: 20.1,
    address: 'Phuket International Airport, Domestic Terminal',
    location: 'Phuket International Airport (HKT)',
    onlineCheckIn: true,
    payNow: true,
    refundable: true,
    pricePerDay: '$21',
    totalPrice: '$63',
    image: '/Content/cars/honda-city.jpg',
    imageAlt: 'Honda City sedan',
    photoCredit: 'Ethan Llamas, CC BY-SA 4.0, via Wikimedia Commons',
  },
  {
    id: 'hkt-convertible-mx5',
    category: 'Convertible',
    model: 'Mazda MX-5 or similar',
    transmission: 'Manual',
    seats: 2,
    fuel: 'Petrol',
    unlimitedMileage: true,
    allWheelDrive: false,
    supplier: 'Andaman Wheels',
    supplierRatingPercent: 84,
    supplierReviewCount: 11,
    locationType: 'Airport',
    freeShuttle: true,
    city: 'Phuket',
    distanceMiles: 20.1,
    address: 'Phuket International Airport, Domestic Terminal',
    location: 'Phuket International Airport (HKT)',
    onlineCheckIn: true,
    payNow: true,
    refundable: true,
    pricePerDay: '$65',
    totalPrice: '$195',
    image: '/Content/cars/mazda-mx5.jpg',
    imageAlt: 'Mazda MX-5 convertible',
    photoCredit: 'Alexander-93, CC BY-SA 4.0, via Wikimedia Commons',
  },
  {
    id: 'hkt-suv-cx5-patong',
    category: 'SUV',
    model: 'Mazda CX-5 or similar',
    transmission: 'Automatic',
    seats: 5,
    fuel: 'Petrol',
    unlimitedMileage: true,
    allWheelDrive: true,
    supplier: 'Island Rentals Samui',
    supplierRatingPercent: 71,
    supplierReviewCount: 7,
    locationType: 'Non-airport',
    freeShuttle: false,
    city: 'Phuket',
    distanceMiles: 0.6,
    address: '92 Thawewong Road, Patong Beach',
    location: 'Patong Beach, Phuket',
    onlineCheckIn: true,
    payNow: false,
    refundable: true,
    pricePerDay: '$44',
    totalPrice: '$132',
    wasPrice: '$150',
    image: '/Content/cars/mazda-cx5.jpg',
    imageAlt: 'Mazda CX-5 SUV',
    photoCredit: 'Alexander Migl, CC BY-SA 4.0, via Wikimedia Commons',
  },
  {
    id: 'cnx-economy-city',
    category: 'Economy',
    model: 'Honda City or similar',
    transmission: 'Automatic',
    seats: 5,
    fuel: 'Petrol',
    unlimitedMileage: true,
    allWheelDrive: false,
    supplier: 'Northern Thai Auto',
    supplierRatingPercent: 71,
    supplierReviewCount: 7,
    locationType: 'Airport',
    freeShuttle: true,
    city: 'Chiang Mai',
    distanceMiles: 2.3,
    address: 'Chiang Mai International Airport, Arrivals Hall',
    location: 'Chiang Mai International Airport (CNX)',
    onlineCheckIn: true,
    payNow: true,
    refundable: true,
    pricePerDay: '$16',
    totalPrice: '$48',
    image: '/Content/cars/honda-city.jpg',
    imageAlt: 'Honda City sedan',
    photoCredit: 'Ethan Llamas, CC BY-SA 4.0, via Wikimedia Commons',
  },
  {
    id: 'cnx-van-hiace',
    category: 'Van',
    model: 'Toyota Hiace or similar',
    transmission: 'Automatic',
    seats: 10,
    fuel: 'Diesel',
    unlimitedMileage: true,
    allWheelDrive: false,
    supplier: 'Northern Thai Auto',
    supplierRatingPercent: 71,
    supplierReviewCount: 7,
    locationType: 'Airport',
    freeShuttle: true,
    city: 'Chiang Mai',
    distanceMiles: 2.3,
    address: 'Chiang Mai International Airport, Arrivals Hall',
    location: 'Chiang Mai International Airport (CNX)',
    onlineCheckIn: true,
    payNow: true,
    refundable: true,
    pricePerDay: '$58',
    totalPrice: '$174',
    image: '/Content/cars/toyota-hiace.jpg',
    imageAlt: 'Toyota Hiace passenger van',
    photoCredit: 'Ethan Llamas, CC BY-SA 4.0, via Wikimedia Commons',
  },
  {
    id: 'cnx-midsize-yaris-nimman',
    category: 'Midsize',
    model: 'Toyota Yaris Hybrid or similar',
    transmission: 'Automatic',
    seats: 5,
    fuel: 'Hybrid',
    unlimitedMileage: true,
    allWheelDrive: false,
    supplier: 'Northern Thai Auto',
    supplierRatingPercent: 71,
    supplierReviewCount: 7,
    locationType: 'Non-airport',
    freeShuttle: false,
    city: 'Chiang Mai',
    distanceMiles: 1.1,
    address: '15 Nimmanhaemin Road, Suthep',
    location: 'Chiang Mai city centre',
    onlineCheckIn: true,
    payNow: false,
    refundable: true,
    pricePerDay: '$29',
    totalPrice: '$87',
    image: '/Content/cars/toyota-yaris.jpg',
    imageAlt: 'Toyota Yaris hatchback',
    photoCredit: 'Nikolai Bulykin, CC BY-SA 4.0, via Wikimedia Commons',
  },
  {
    id: 'usm-compact-jazz',
    category: 'Compact',
    model: 'Honda Jazz or similar',
    transmission: 'Automatic',
    seats: 5,
    fuel: 'Hybrid',
    unlimitedMileage: true,
    allWheelDrive: false,
    supplier: 'Island Rentals Samui',
    supplierRatingPercent: 71,
    supplierReviewCount: 7,
    locationType: 'Airport',
    freeShuttle: true,
    city: 'Koh Samui',
    distanceMiles: 1.8,
    address: 'Samui International Airport, Open-air Arrivals',
    location: 'Koh Samui Airport (USM)',
    onlineCheckIn: false,
    payNow: false,
    refundable: true,
    pricePerDay: '$24',
    totalPrice: '$72',
    image: '/Content/cars/honda-jazz.jpg',
    imageAlt: 'Honda Jazz hatchback',
    photoCredit: 'Alexander-93, CC BY-SA 4.0, via Wikimedia Commons',
  },
  {
    id: 'kbv-suv-cx5',
    category: 'SUV',
    model: 'Mazda CX-5 or similar',
    transmission: 'Automatic',
    seats: 5,
    fuel: 'Petrol',
    unlimitedMileage: true,
    allWheelDrive: true,
    supplier: 'Krabi Coastal Cars',
    supplierRatingPercent: 58,
    supplierReviewCount: 3,
    locationType: 'Airport',
    freeShuttle: true,
    city: 'Krabi',
    distanceMiles: 8.7,
    address: 'Krabi International Airport, Terminal 2',
    location: 'Krabi Airport (KBV)',
    onlineCheckIn: true,
    payNow: true,
    refundable: true,
    pricePerDay: '$38',
    totalPrice: '$114',
    image: '/Content/cars/mazda-cx5.jpg',
    imageAlt: 'Mazda CX-5 SUV',
    photoCredit: 'Alexander Migl, CC BY-SA 4.0, via Wikimedia Commons',
  },
  {
    id: 'kbv-mini-jazz-aonang',
    category: 'Mini',
    model: 'Honda Jazz or similar',
    transmission: 'Manual',
    seats: 4,
    fuel: 'Petrol',
    unlimitedMileage: false,
    allWheelDrive: false,
    supplier: 'Krabi Coastal Cars',
    supplierRatingPercent: 58,
    supplierReviewCount: 3,
    locationType: 'Non-airport',
    freeShuttle: false,
    city: 'Krabi',
    distanceMiles: 0.4,
    address: '247 Moo 2, Ao Nang Beach',
    location: 'Ao Nang, Krabi',
    onlineCheckIn: false,
    payNow: false,
    refundable: true,
    pricePerDay: '$15',
    totalPrice: '$45',
    wasPrice: '$52',
    image: '/Content/cars/honda-jazz.jpg',
    imageAlt: 'Honda Jazz hatchback',
    photoCredit: 'Alexander-93, CC BY-SA 4.0, via Wikimedia Commons',
  },
];
