import type { Cruise } from './types';

/*
 * Mock sailings on the three waters this site covers: the Andaman Sea, the
 * Gulf of Thailand and the Chao Phraya river. No live inventory — every fare,
 * score and review count below is fixed sample data, kept internally
 * consistent so the cards read like real listings.
 *
 * `bestMonths` reflects real seasonality: the Andaman coast is settled roughly
 * November to April, the Gulf runs later into the year, and the river sails
 * all twelve months.
 */

const ANDAMAN_SEASON = [11, 12, 1, 2, 3, 4];
const GULF_SEASON = [12, 1, 2, 3, 4, 5, 6, 7, 8, 9];
const ALL_YEAR = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12];

export const cruises: Cruise[] = [
  {
    id: 'andaman-island-hopper-3n',
    line: 'Andaman Star Cruises',
    ship: 'MS Andaman Star',
    region: 'Andaman Sea',
    nights: 3,
    departurePort: 'Phuket',
    ports: ['Phuket', 'Phi Phi Islands', 'Krabi', 'Phuket'],
    capacity: 48,
    cabins: ['Inside twin', 'Sea-view double', 'Balcony suite'],
    departureDays: ['Mon', 'Thu'],
    includes: ['All meals on board', 'Guided shore stops', 'Snorkelling gear', 'Port fees'],
    highlights: ['Anchor overnight off Phi Phi Leh', 'Dawn swim before the day boats', 'Railay by tender'],
    score: 9.4,
    reviewCount: 86,
    freeCancellation: true,
    bestMonths: ANDAMAN_SEASON,
    price: '$420',
    image: '/Content/phi-phi-island-tour-700-2.jpg',
    imageAlt: 'Phi Phi Islands, Andaman Sea',
  },
  {
    id: 'andaman-maya-bay-explorer-2n',
    line: 'Siam Sea Voyages',
    ship: 'MS Siam Explorer',
    region: 'Andaman Sea',
    nights: 2,
    departurePort: 'Krabi',
    ports: ['Krabi', 'Maya Bay', 'Railay Beach'],
    capacity: 32,
    cabins: ['Inside twin', 'Sea-view double'],
    departureDays: ['Wed', 'Sat'],
    includes: ['All meals on board', 'Kayaks', 'National park fees'],
    highlights: ['Maya Bay before the ferries', 'Kayaking into the Railay lagoons'],
    score: 9.0,
    reviewCount: 124,
    freeCancellation: true,
    bestMonths: ANDAMAN_SEASON,
    price: '$295',
    image: '/Content/maya-bay-phi-phi-leh-700-2.jpg',
    imageAlt: 'Maya Bay, Phi Phi Leh',
  },
  {
    id: 'andaman-phang-nga-bay-3n',
    line: 'Siam Sea Voyages',
    ship: 'MS Siam Explorer',
    region: 'Andaman Sea',
    nights: 3,
    departurePort: 'Phuket',
    ports: ['Phuket', 'Phang Nga Bay', 'James Bond Island', 'Phuket'],
    capacity: 32,
    cabins: ['Inside twin', 'Sea-view double'],
    departureDays: ['Tue', 'Fri'],
    includes: ['All meals on board', 'Sea-cave canoeing', 'National park fees'],
    highlights: ['Canoe into the hongs at slack tide', 'Sunset among the karsts'],
    score: 9.6,
    reviewCount: 71,
    freeCancellation: true,
    bestMonths: ANDAMAN_SEASON,
    price: '$445',
    image: '/Content/phuket-phang-nga-bay-tour-700-2.jpg',
    imageAlt: 'Phang Nga Bay',
  },
  {
    id: 'andaman-similan-liveaboard-4n',
    line: 'Andaman Star Cruises',
    ship: 'MS Andaman Pearl',
    region: 'Andaman Sea',
    nights: 4,
    departurePort: 'Khao Lak',
    ports: ['Khao Lak', 'Similan Islands', 'Koh Bon', 'Khao Lak'],
    capacity: 24,
    cabins: ['Bunk twin', 'Sea-view double'],
    departureDays: ['Sun'],
    includes: ['All meals on board', 'Up to 12 dives', 'Tanks and weights', 'Marine park fees'],
    highlights: ['Similan granite swim-throughs', 'Manta season at Koh Bon', 'Night dive off Koh Tachai'],
    score: 9.8,
    reviewCount: 43,
    freeCancellation: false,
    bestMonths: [11, 12, 1, 2, 3, 4],
    price: '$980',
    image: '/Content/10-Best-Attractions-Thailand-Beaches.webp',
    imageAlt: 'Clear water over a Thai reef',
  },
  {
    id: 'andaman-koh-lanta-sunset-day',
    line: 'Andaman Star Cruises',
    ship: 'MY Andaman Breeze',
    region: 'Andaman Sea',
    nights: 0,
    departurePort: 'Krabi',
    ports: ['Krabi', 'Koh Lanta', 'Krabi'],
    capacity: 40,
    cabins: ['Open deck seating'],
    departureDays: ['Mon', 'Wed', 'Fri', 'Sun'],
    includes: ['Dinner on deck', 'Soft drinks', 'Snorkelling stop'],
    highlights: ['Sunset off Koh Lanta', 'Swim stop on the way back'],
    score: 8.8,
    reviewCount: 158,
    freeCancellation: true,
    bestMonths: ANDAMAN_SEASON,
    price: '$78',
    image: '/Content/krabi-Railay-700-2.jpg',
    imageAlt: 'Limestone cliffs above the water near Krabi',
  },
  {
    id: 'gulf-koh-samui-getaway-4n',
    line: 'Gulf Coast Cruising',
    ship: 'MS Gulf Pearl',
    region: 'Gulf of Thailand',
    nights: 4,
    departurePort: 'Koh Samui',
    ports: ['Koh Samui', 'Koh Phangan', 'Koh Tao', 'Koh Samui'],
    capacity: 60,
    cabins: ['Inside twin', 'Sea-view double', 'Balcony suite'],
    departureDays: ['Sat'],
    includes: ['All meals on board', 'Guided shore stops', 'Snorkelling gear', 'Port fees'],
    highlights: ['Koh Tao reefs at first light', 'A night at anchor off Phangan'],
    score: 9.2,
    reviewCount: 112,
    freeCancellation: true,
    bestMonths: GULF_SEASON,
    price: '$560',
    image: '/Content/thailand-koh-samui-700-2.jpg',
    imageAlt: 'The Big Buddha at Wat Phra Yai, Koh Samui',
  },
  {
    id: 'gulf-pattaya-weekend-2n',
    line: 'Gulf Coast Cruising',
    ship: 'MS Gulf Pearl',
    region: 'Gulf of Thailand',
    nights: 2,
    departurePort: 'Pattaya',
    ports: ['Pattaya', 'Koh Larn', 'Pattaya'],
    capacity: 60,
    cabins: ['Inside twin', 'Sea-view double'],
    departureDays: ['Fri'],
    includes: ['All meals on board', 'Beach transfer', 'Port fees'],
    highlights: ['Koh Larn beaches without the day crowds', 'Deck dinner on the way back'],
    score: 8.4,
    reviewCount: 96,
    freeCancellation: true,
    bestMonths: GULF_SEASON,
    price: '$210',
    image: '/Content/thailand-pattaya-koh-larn-700-1.jpg',
    imageAlt: 'Koh Larn, near Pattaya',
  },
  {
    id: 'gulf-ang-thong-marine-park-3n',
    line: 'Gulf Coast Cruising',
    ship: 'MS Gulf Explorer',
    region: 'Gulf of Thailand',
    nights: 3,
    departurePort: 'Koh Samui',
    ports: ['Koh Samui', 'Ang Thong Marine Park', 'Koh Wua Talap', 'Koh Samui'],
    capacity: 44,
    cabins: ['Inside twin', 'Sea-view double'],
    departureDays: ['Tue'],
    includes: ['All meals on board', 'Kayaks', 'Marine park fees', 'Guided viewpoint hike'],
    highlights: ['The Emerald Lake on Koh Mae Ko', 'Kayaking the limestone channels'],
    score: 9.4,
    reviewCount: 67,
    freeCancellation: true,
    bestMonths: GULF_SEASON,
    price: '$465',
    image: '/Content/thailand-koh-samui-700-4.jpg',
    imageAlt: 'Islands scattered across the Gulf of Thailand',
  },
  {
    id: 'gulf-koh-tao-dive-liveaboard-3n',
    line: 'Siam Sea Voyages',
    ship: 'MY Gulf Diver',
    region: 'Gulf of Thailand',
    nights: 3,
    departurePort: 'Koh Tao',
    ports: ['Koh Tao', 'Chumphon Pinnacle', 'Sail Rock', 'Koh Tao'],
    capacity: 18,
    cabins: ['Bunk twin', 'Sea-view double'],
    departureDays: ['Thu'],
    includes: ['All meals on board', 'Up to 9 dives', 'Tanks and weights'],
    highlights: ['Whale sharks at Sail Rock in season', 'Chumphon Pinnacle at dawn'],
    score: 9.6,
    reviewCount: 38,
    freeCancellation: false,
    bestMonths: [3, 4, 5, 6, 7, 8, 9],
    price: '$690',
    image: '/Content/bophut-fisherman-village.jpg',
    imageAlt: 'Fishing boats moored on Koh Samui',
  },
  {
    id: 'chao-phraya-dinner-cruise',
    line: 'Chao Phraya River Line',
    ship: 'MV River Jewel',
    region: 'Chao Phraya River',
    nights: 0,
    departurePort: 'Bangkok',
    ports: ['Bangkok riverside', 'Wat Arun', 'Grand Palace'],
    capacity: 120,
    cabins: ['Open upper deck', 'Air-conditioned lower deck'],
    departureDays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    includes: ['Dinner buffet', 'Live acoustic set', 'Pier transfer'],
    highlights: ['Wat Arun floodlit from the water', 'Rama VIII bridge turn'],
    score: 9.0,
    reviewCount: 341,
    freeCancellation: true,
    bestMonths: ALL_YEAR,
    price: '$65',
    image: '/Content/bangkok-night-market-700-1.jpg',
    imageAlt: 'Bangkok riverside at night',
  },
  {
    id: 'chao-phraya-ayutthaya-2n',
    line: 'Chao Phraya River Line',
    ship: 'MV River Orchid',
    region: 'Chao Phraya River',
    nights: 2,
    departurePort: 'Bangkok',
    ports: ['Bangkok', 'Koh Kret', 'Bang Pa-In', 'Ayutthaya'],
    capacity: 28,
    cabins: ['River-view twin', 'River-view double'],
    departureDays: ['Wed', 'Sun'],
    includes: ['All meals on board', 'Guided temple stops', 'Return coach from Ayutthaya'],
    highlights: ['Wake up moored at Bang Pa-In', 'Ayutthaya ruins before the coaches'],
    score: 9.4,
    reviewCount: 54,
    freeCancellation: true,
    bestMonths: ALL_YEAR,
    price: '$385',
    image: '/Content/ayutthaya-historic-city-700-4.jpg',
    imageAlt: 'Ruined stupas at Ayutthaya',
  },
  {
    id: 'chao-phraya-morning-market-day',
    line: 'Chao Phraya River Line',
    ship: 'MV River Lotus',
    region: 'Chao Phraya River',
    nights: 0,
    departurePort: 'Bangkok',
    ports: ['Bangkok', 'Khlong Bang Luang', 'Bangkok'],
    capacity: 24,
    cabins: ['Open longtail seating'],
    departureDays: ['Mon', 'Wed', 'Fri', 'Sat'],
    includes: ['Breakfast on board', 'Canal guide', 'Market stop'],
    highlights: ['Canal-side houses on stilts', 'Breakfast bought from a boat'],
    score: 8.6,
    reviewCount: 187,
    freeCancellation: true,
    bestMonths: ALL_YEAR,
    price: '$42',
    image: '/Content/10-Best-Attractions-Thailand-Floating-Markets.webp',
    imageAlt: 'A floating market on a Bangkok canal',
  },
];
