import type { Cruise } from './types';

/** Mock sailings. No live inventory. */
export const cruises: Cruise[] = [
  {
    id: "andaman-island-hopper-3n",
    line: "Andaman Star Cruises",
    ship: "MS Andaman Star",
    region: "Andaman Sea",
    nights: 3,
    departurePort: "Phuket",
    ports: ["Phuket", "Phi Phi Islands", "Krabi", "Phuket"],
    price: "$420",
    image: "/Content/phi-phi-island-tour-700-2.jpg",
    imageAlt: "Phi Phi Islands, Andaman Sea",
  },
  {
    id: "andaman-maya-bay-explorer-2n",
    line: "Siam Sea Voyages",
    ship: "MS Siam Explorer",
    region: "Andaman Sea",
    nights: 2,
    departurePort: "Krabi",
    ports: ["Krabi", "Maya Bay", "Railay Beach"],
    price: "$295",
    image: "/Content/maya-bay-phi-phi-leh-700-2.jpg",
    imageAlt: "Maya Bay, Phi Phi Leh",
  },
  {
    id: "gulf-koh-samui-getaway-4n",
    line: "Gulf Coast Cruising",
    ship: "MS Gulf Pearl",
    region: "Gulf of Thailand",
    nights: 4,
    departurePort: "Koh Samui",
    ports: ["Koh Samui", "Koh Phangan", "Koh Tao", "Koh Samui"],
    price: "$560",
    image: "/Content/thailand-koh-samui-700-2.jpg",
    imageAlt: "Koh Samui coastline",
  },
  {
    id: "gulf-pattaya-weekend-2n",
    line: "Gulf Coast Cruising",
    ship: "MS Gulf Pearl",
    region: "Gulf of Thailand",
    nights: 2,
    departurePort: "Pattaya",
    ports: ["Pattaya", "Koh Larn", "Pattaya"],
    price: "$210",
    image: "/Content/thailand-pattaya-koh-larn-700-1.jpg",
    imageAlt: "Koh Larn, near Pattaya",
  },
  {
    id: "chao-phraya-dinner-cruise",
    line: "Chao Phraya River Line",
    ship: "MV River Jewel",
    region: "Chao Phraya River",
    nights: 0,
    departurePort: "Bangkok",
    ports: ["Bangkok riverside", "Wat Arun", "Grand Palace"],
    price: "$65",
    image: "/Content/bangkok-night-market-700-1.jpg",
    imageAlt: "Bangkok riverside at night",
  },
  {
    id: "andaman-phang-nga-bay-3n",
    line: "Siam Sea Voyages",
    ship: "MS Siam Explorer",
    region: "Andaman Sea",
    nights: 3,
    departurePort: "Phuket",
    ports: ["Phuket", "Phang Nga Bay", "James Bond Island", "Phuket"],
    price: "$445",
    image: "/Content/phuket-phang-nga-bay-tour-700-2.jpg",
    imageAlt: "Phang Nga Bay",
  },
];
