import type { Destination } from './types';

/**
 * The ten destinations in the "Where to go" feed. Map URLs, gallery alt text and
 * the "Save X" / "See X tours" labels are all derived from `name` and `coords`
 * in <ListingCard>, so they are deliberately not repeated here.
 */
export const destinations: Destination[] = [
  {
    slug: "bangkok",
    name: "Bangkok",
    sub: "Temples, street food, river life",
    facts: "3–4 day trip · Best Nov–Feb",
    price: "From $65",
    rating: 4.9,
    ratingCount: 312,
    badge: "Guest favorite",
    badgeAlt: false,
    coords: "13.7563, 100.5018",
    thumbAlt: "The Grand Palace, Bangkok",
    about: "Bangkok moves at every speed at once: gilded temple spires above, street-food carts and river ferries below. Spend a morning at the Grand Palace and Wat Traimit's golden Buddha, then let the evening unwind in Chinatown's Yaowarat night market.",
    images: [
      "/Content/bangkok-grand-palace-700-2.jpg",
      "/Content/bangkok-night-market-700-1.jpg",
      "/Content/bangkok-wat-traimit-700-2.jpg",
      "/Content/chinatown-bangkok-yaowarat-700-1.jpg",
    ],
  },
  {
    slug: "phuket",
    name: "Phuket",
    sub: "Beaches, old town, boat life",
    facts: "4–5 day trip · Best Nov–Apr",
    price: "From $74",
    rating: 4.8,
    ratingCount: 268,
    badge: "Popular pick",
    badgeAlt: true,
    coords: "7.8804, 98.3923",
    thumbAlt: "Phuket Old Town",
    about: "Phuket pairs Sino-Portuguese shophouses in the old town with long-tail boats out to limestone bays. Base yourself near Old Town and day-trip out to Phang Nga's karst-studded waters.",
    images: [
      "/Content/phuket-old-town-700-1.jpg",
      "/Content/phuket-old-town-700-2.jpg",
      "/Content/phuket-phang-nga-bay-tour-700-2.jpg",
    ],
  },
  {
    slug: "chiang-mai",
    name: "Chiang Mai",
    sub: "Mountains, markets, slow mornings",
    facts: "3 day trip · Best Nov–Feb",
    price: "From $58",
    rating: 5.0,
    ratingCount: 190,
    badge: "Guest favorite",
    badgeAlt: false,
    coords: "18.7883, 98.9853",
    thumbAlt: "Doi Inthanon National Park, Chiang Mai",
    about: "Chiang Mai trades the coast for misty mountains, hilltop temples like Wat Phra Singh, and a walled old town that comes alive at the night market. A relaxed base for cooking classes and slow mornings.",
    images: [
      "/Content/chiangmai-doi-national-park-700-1.jpg",
      "/Content/chiangmai-night-700-1.jpg",
      "/Content/chiang-mai-cooking-class-700-3.jpg",
      "/Content/10-Best-Attractions-Thailand-Wat-Phra-Singh.jpg",
    ],
  },
  {
    slug: "chiang-rai",
    name: "Chiang Rai",
    sub: "Golden Triangle, white temple",
    facts: "2 day trip · Best Nov–Feb",
    price: "From $145",
    rating: 4.8,
    ratingCount: 97,
    badge: "Popular pick",
    badgeAlt: true,
    coords: "19.9105, 99.8406",
    thumbAlt: "White Temple, Chiang Rai",
    about: "Chiang Rai's contemporary temples — the dazzling White Temple and the stark Black House — sit near the Golden Triangle, where Thailand, Laos, and Myanmar meet along the Mekong.",
    images: [
      "/Content/chiang-rai-white-temple-700-1.jpg",
      "/Content/chiangrai-baan-dam-700-1.jpg",
      "/Content/thailand-golden-triangle-700-1.jpg",
    ],
  },
  {
    slug: "krabi",
    name: "Krabi",
    sub: "Limestone cliffs, hidden lagoons",
    facts: "3–4 day trip · Best Dec–Mar",
    price: "From $89",
    rating: 4.9,
    ratingCount: 221,
    badge: "Guest favorite",
    badgeAlt: false,
    coords: "8.0863, 98.9063",
    thumbAlt: "Railay Beach, Krabi",
    about: "Krabi's karst cliffs rise straight out of turquoise water, framing beaches only reachable by longtail boat. Base at Railay or Ao Nang and hop out to Phi Phi's hidden lagoons and Phang Nga's sea caves.",
    images: [
      "/Content/krabi-Railay-700-2.jpg",
      "/Content/maya-bay-phi-phi-leh-700-2.jpg",
      "/Content/phi-phi-island-tour-700-2.jpg",
      "/Content/canoeing-to-cave-james-bond-island-tour-700-2.jpg",
    ],
  },
  {
    slug: "ayutthaya",
    name: "Ayutthaya",
    sub: "Ancient capital, quiet ruins",
    facts: "Day trip · Best Nov–Feb",
    price: "From $52",
    rating: 4.7,
    ratingCount: 154,
    badge: "Popular pick",
    badgeAlt: true,
    coords: "14.3532, 100.5689",
    thumbAlt: "Ayutthaya Historic City",
    about: "Once Siam's capital, Ayutthaya is now a quiet field of brick temple ruins and headless Buddha statues, easily reached as a day trip north of Bangkok by train or river cruise.",
    images: [
      "/Content/ayutthaya-historic-city-700-4.jpg",
      "/Content/ayutthaya-chao-sam-phraya-national-museum-700-2.jpg",
      "/Content/10-Best-Attractions-Thailand-Ayutthaya-Historical-Park.jpg",
    ],
  },
  {
    slug: "koh-samui",
    name: "Koh Samui",
    sub: "Palm coast, fishing villages, easy island life",
    facts: "3–4 day trip · Best Dec–Apr",
    price: "From $95",
    rating: 4.8,
    ratingCount: 176,
    badge: "Popular pick",
    badgeAlt: true,
    coords: "9.5120, 100.0136",
    thumbAlt: "Koh Samui coastline",
    about: "Koh Samui swaps backpacker chaos for palm-lined coastline and the low-key charm of Bophut's Fisherman's Village. A short flight from Bangkok gets you straight to island time.",
    images: [
      "/Content/thailand-koh-samui-700-2.jpg",
      "/Content/thailand-koh-samui-700-4.jpg",
      "/Content/bophut-fisherman-village.jpg",
    ],
  },
  {
    slug: "sukhothai",
    name: "Sukhothai",
    sub: "Original capital, lotus ponds, dawn temple light",
    facts: "2 day trip · Best Nov–Feb",
    price: "From $68",
    rating: 4.9,
    ratingCount: 88,
    badge: "Guest favorite",
    badgeAlt: false,
    coords: "17.0195, 99.7031",
    thumbAlt: "Wat Mahathat, Sukhothai Historical Park",
    about: "Thailand's first capital is a UNESCO park of lotus ponds and weathered Buddha statues, best explored slowly by bicycle at sunrise before the heat and the crowds arrive.",
    images: [
      "/Content/10-Best-Attractions-Thailand-Sukhothai-Wat.jpg",
      "/Content/sukhothai.jpg",
    ],
  },
  {
    slug: "khao-yai-national-park",
    name: "Khao Yai National Park",
    sub: "Rainforest trails, waterfalls, wild elephants",
    facts: "2 day trip · Best Nov–Feb",
    price: "From $78",
    rating: 4.8,
    ratingCount: 74,
    badge: "Popular pick",
    badgeAlt: true,
    coords: "14.4386, 101.3719",
    thumbAlt: "Khao Yai National Park",
    about: "One of Thailand's oldest national parks, Khao Yai is a UNESCO World Heritage rainforest a few hours from Bangkok — home to wild elephants, hornbills, and waterfall-fed hiking trails.",
    images: [
      "/Content/10-Best-Attractions-Thailand-Khao-Yai-National-Park.webp",
      "/Content/khao-yai-park.jpg",
    ],
  },
  {
    slug: "kanchanaburi",
    name: "Kanchanaburi",
    sub: "River Kwai bridge, waterfalls, wartime history",
    facts: "Day trip · Best Nov–Feb",
    price: "From $60",
    rating: 4.6,
    ratingCount: 109,
    badge: "Guest favorite",
    badgeAlt: false,
    coords: "14.0227, 99.5328",
    thumbAlt: "Bridge over the River Kwai, Kanchanaburi",
    about: "Kanchanaburi pairs the sobering history of the bridge over the River Kwai with the turquoise, seven-tiered pools of Erawan National Park — a full day of contrast a couple of hours from Bangkok.",
    images: [
      "/Content/kanchanaburi-bridge-over-the-river-kwai-700-2.jpg",
      "/Content/kanchanaburi-erawan-national-park-700-1.jpg",
      "/Content/10-Best-Attractions-Thailand-Kanchanaburi.webp",
    ],
  },
];
