import type { Flight } from './types';

/** Mock schedule between the cities this site actually covers. No live inventory. */
export const flights: Flight[] = [
  {
    id: "bkk-hkt-th201",
    airline: "Thai Coastal Air",
    flightNumber: "TC201",
    fromCode: "BKK",
    fromCity: "Bangkok",
    toCode: "HKT",
    toCity: "Phuket",
    departTime: "07:15",
    arriveTime: "08:45",
    duration: "1h 30m",
    stops: 0,
    cabin: "Economy",
    price: "$58",
  },
  {
    id: "bkk-hkt-th455",
    airline: "Siam Skyways",
    flightNumber: "SS455",
    fromCode: "BKK",
    fromCity: "Bangkok",
    toCode: "HKT",
    toCity: "Phuket",
    departTime: "14:20",
    arriveTime: "15:50",
    duration: "1h 30m",
    stops: 0,
    cabin: "Economy",
    price: "$64",
  },
  {
    id: "bkk-cnx-th110",
    airline: "Thai Coastal Air",
    flightNumber: "TC110",
    fromCode: "BKK",
    fromCity: "Bangkok",
    toCode: "CNX",
    toCity: "Chiang Mai",
    departTime: "09:05",
    arriveTime: "10:20",
    duration: "1h 15m",
    stops: 0,
    cabin: "Economy",
    price: "$49",
  },
  {
    id: "bkk-cnx-th880",
    airline: "Golden Orchid Airlines",
    flightNumber: "GO880",
    fromCode: "BKK",
    fromCity: "Bangkok",
    toCode: "CNX",
    toCity: "Chiang Mai",
    departTime: "18:40",
    arriveTime: "19:55",
    duration: "1h 15m",
    stops: 0,
    cabin: "Business",
    price: "$142",
  },
  {
    id: "bkk-usm-th330",
    airline: "Siam Skyways",
    flightNumber: "SS330",
    fromCode: "BKK",
    fromCity: "Bangkok",
    toCode: "USM",
    toCity: "Koh Samui",
    departTime: "10:30",
    arriveTime: "11:45",
    duration: "1h 15m",
    stops: 0,
    cabin: "Economy",
    price: "$95",
  },
  {
    id: "bkk-kbv-th602",
    airline: "Golden Orchid Airlines",
    flightNumber: "GO602",
    fromCode: "BKK",
    fromCity: "Bangkok",
    toCode: "KBV",
    toCity: "Krabi",
    departTime: "06:50",
    arriveTime: "08:10",
    duration: "1h 20m",
    stops: 0,
    cabin: "Economy",
    price: "$61",
  },
  {
    id: "hkt-cnx-th740",
    airline: "Thai Coastal Air",
    flightNumber: "TC740",
    fromCode: "HKT",
    fromCity: "Phuket",
    toCode: "CNX",
    toCity: "Chiang Mai",
    departTime: "12:10",
    arriveTime: "14:05",
    duration: "1h 55m",
    stops: 1,
    cabin: "Economy",
    price: "$88",
  },
  {
    id: "cnx-bkk-th115",
    airline: "Golden Orchid Airlines",
    flightNumber: "GO115",
    fromCode: "CNX",
    fromCity: "Chiang Mai",
    toCode: "BKK",
    toCity: "Bangkok",
    departTime: "20:15",
    arriveTime: "21:30",
    duration: "1h 15m",
    stops: 0,
    cabin: "Economy",
    price: "$47",
  },
];
