import type { Flight } from './types';

/*
 * Mock schedule between the cities this site actually covers. No live
 * inventory and no live pricing — every fare, rating and review count below is
 * fixed sample data, kept internally consistent (each airline always carries
 * the same rating, each fare's total always exceeds its per-traveler price)
 * so the results page reads like a real one.
 */
export const flights: Flight[] = [
  {
    id: 'bkk-hkt-th201',
    airline: 'Thai Coastal Air',
    airlineCode: 'TC',
    flightNumber: 'TC201',
    aircraft: 'Airbus A320neo or similar',
    fromCode: 'BKK',
    fromCity: 'Bangkok',
    fromAirport: 'Suvarnabhumi Airport',
    toCode: 'HKT',
    toCity: 'Phuket',
    toAirport: 'Phuket International Airport',
    terminal: 'Terminal 2',
    departTime: '07:15',
    arriveTime: '08:45',
    duration: '1h 30m',
    durationMinutes: 90,
    stops: 0,
    cabin: 'Economy',
    carryOn: '1 carry-on',
    checkedBag: true,
    wifi: true,
    meal: false,
    onlineCheckIn: true,
    payNow: true,
    refundable: true,
    ratingPercent: 79,
    reviewCount: 24,
    price: '$58',
    totalPrice: '$124',
    image: '/Content/phuket-phang-nga-bay-tour-700-2.jpg',
    imageAlt: 'Limestone karsts in Phang Nga Bay, north of Phuket',
  },
  {
    id: 'bkk-hkt-th455',
    airline: 'Siam Skyways',
    airlineCode: 'SS',
    flightNumber: 'SS455',
    aircraft: 'Boeing 737-800 or similar',
    fromCode: 'BKK',
    fromCity: 'Bangkok',
    fromAirport: 'Don Mueang Airport',
    toCode: 'HKT',
    toCity: 'Phuket',
    toAirport: 'Phuket International Airport',
    terminal: 'Terminal 1',
    departTime: '14:20',
    arriveTime: '15:50',
    duration: '1h 30m',
    durationMinutes: 90,
    stops: 0,
    cabin: 'Economy',
    carryOn: '1 carry-on',
    checkedBag: false,
    wifi: false,
    meal: false,
    onlineCheckIn: true,
    payNow: false,
    refundable: true,
    ratingPercent: 58,
    reviewCount: 3,
    price: '$64',
    totalPrice: '$139',
    wasPrice: '$158',
    image: '/Content/phuket-old-town-700-2.jpg',
    imageAlt: 'Sino-Portuguese shophouses in Phuket Old Town',
  },
  {
    id: 'bkk-cnx-th110',
    airline: 'Thai Coastal Air',
    airlineCode: 'TC',
    flightNumber: 'TC110',
    aircraft: 'Airbus A320neo or similar',
    fromCode: 'BKK',
    fromCity: 'Bangkok',
    fromAirport: 'Suvarnabhumi Airport',
    toCode: 'CNX',
    toCity: 'Chiang Mai',
    toAirport: 'Chiang Mai International Airport',
    terminal: 'Terminal 2',
    departTime: '09:05',
    arriveTime: '10:20',
    duration: '1h 15m',
    durationMinutes: 75,
    stops: 0,
    cabin: 'Economy',
    carryOn: '1 carry-on',
    checkedBag: true,
    wifi: true,
    meal: false,
    onlineCheckIn: true,
    payNow: true,
    refundable: true,
    ratingPercent: 79,
    reviewCount: 24,
    price: '$49',
    totalPrice: '$106',
    image: '/Content/chiangmai-doi-national-park-700-1.jpg',
    imageAlt: 'Gardens at Doi Inthanon national park, Chiang Mai',
  },
  {
    id: 'bkk-cnx-th880',
    airline: 'Golden Orchid Airlines',
    airlineCode: 'GO',
    flightNumber: 'GO880',
    aircraft: 'Airbus A321neo or similar',
    fromCode: 'BKK',
    fromCity: 'Bangkok',
    fromAirport: 'Suvarnabhumi Airport',
    toCode: 'CNX',
    toCity: 'Chiang Mai',
    toAirport: 'Chiang Mai International Airport',
    terminal: 'Terminal 1',
    departTime: '18:40',
    arriveTime: '19:55',
    duration: '1h 15m',
    durationMinutes: 75,
    stops: 0,
    cabin: 'Business',
    carryOn: '2 carry-on',
    checkedBag: true,
    wifi: true,
    meal: true,
    onlineCheckIn: true,
    payNow: true,
    refundable: true,
    ratingPercent: 84,
    reviewCount: 11,
    price: '$142',
    totalPrice: '$302',
    image: '/Content/chiangmai-night-700-1.jpg',
    imageAlt: 'Sky lanterns released over Chiang Mai at the Yi Peng festival',
  },
  {
    id: 'bkk-usm-th330',
    airline: 'Siam Skyways',
    airlineCode: 'SS',
    flightNumber: 'SS330',
    aircraft: 'ATR 72-600 or similar',
    fromCode: 'BKK',
    fromCity: 'Bangkok',
    fromAirport: 'Don Mueang Airport',
    toCode: 'USM',
    toCity: 'Koh Samui',
    toAirport: 'Samui International Airport',
    terminal: 'Terminal 1',
    departTime: '10:30',
    arriveTime: '11:45',
    duration: '1h 15m',
    durationMinutes: 75,
    stops: 0,
    cabin: 'Economy',
    carryOn: '1 carry-on',
    checkedBag: true,
    wifi: false,
    meal: true,
    onlineCheckIn: false,
    payNow: false,
    refundable: true,
    ratingPercent: 58,
    reviewCount: 3,
    price: '$95',
    totalPrice: '$203',
    image: '/Content/thailand-koh-samui-700-2.jpg',
    imageAlt: 'The Big Buddha at Wat Phra Yai, Koh Samui',
  },
  {
    id: 'bkk-kbv-th602',
    airline: 'Golden Orchid Airlines',
    airlineCode: 'GO',
    flightNumber: 'GO602',
    aircraft: 'Airbus A320neo or similar',
    fromCode: 'BKK',
    fromCity: 'Bangkok',
    fromAirport: 'Suvarnabhumi Airport',
    toCode: 'KBV',
    toCity: 'Krabi',
    toAirport: 'Krabi International Airport',
    terminal: 'Terminal 1',
    departTime: '06:50',
    arriveTime: '08:10',
    duration: '1h 20m',
    durationMinutes: 80,
    stops: 0,
    cabin: 'Economy',
    carryOn: '1 carry-on',
    checkedBag: true,
    wifi: true,
    meal: false,
    onlineCheckIn: true,
    payNow: true,
    refundable: true,
    ratingPercent: 84,
    reviewCount: 11,
    price: '$61',
    totalPrice: '$131',
    wasPrice: '$149',
    image: '/Content/krabi-Railay-700-2.jpg',
    imageAlt: 'Railay Beach beneath its limestone headland, Krabi',
  },
  {
    id: 'hkt-cnx-th740',
    airline: 'Thai Coastal Air',
    airlineCode: 'TC',
    flightNumber: 'TC740',
    aircraft: 'Boeing 737-800 or similar',
    fromCode: 'HKT',
    fromCity: 'Phuket',
    fromAirport: 'Phuket International Airport',
    toCode: 'CNX',
    toCity: 'Chiang Mai',
    toAirport: 'Chiang Mai International Airport',
    terminal: 'Terminal 1',
    departTime: '12:10',
    arriveTime: '14:05',
    duration: '1h 55m',
    durationMinutes: 115,
    stops: 1,
    cabin: 'Economy',
    carryOn: '1 carry-on',
    checkedBag: false,
    wifi: false,
    meal: false,
    onlineCheckIn: true,
    payNow: false,
    refundable: true,
    ratingPercent: 79,
    reviewCount: 24,
    price: '$88',
    totalPrice: '$188',
    image: '/Content/10-Best-Attractions-Thailand-Wat-Phra-Singh.jpg',
    imageAlt: 'Wat Phra Singh in Chiang Mai’s old city',
  },
  {
    id: 'cnx-bkk-th115',
    airline: 'Golden Orchid Airlines',
    airlineCode: 'GO',
    flightNumber: 'GO115',
    aircraft: 'Airbus A321neo or similar',
    fromCode: 'CNX',
    fromCity: 'Chiang Mai',
    fromAirport: 'Chiang Mai International Airport',
    toCode: 'BKK',
    toCity: 'Bangkok',
    toAirport: 'Suvarnabhumi Airport',
    terminal: 'Terminal 1',
    departTime: '20:15',
    arriveTime: '21:30',
    duration: '1h 15m',
    durationMinutes: 75,
    stops: 0,
    cabin: 'Economy',
    carryOn: '1 carry-on',
    checkedBag: true,
    wifi: true,
    meal: false,
    onlineCheckIn: true,
    payNow: true,
    refundable: true,
    ratingPercent: 84,
    reviewCount: 11,
    price: '$47',
    totalPrice: '$101',
    image: '/Content/bangkok-grand-palace-700-2.jpg',
    imageAlt: 'The Grand Palace in Bangkok',
  },
];
