import type { PackageDeal } from './types';

/*
 * Mock flight + stay bundles, grouped on the page by the destination they go
 * to. No live inventory: every price, star rating and date window below is
 * fixed sample data, kept internally consistent so the deal rows read like
 * real ones. Prices are per person, based on two sharing.
 */
export const packages: PackageDeal[] = [
  // ---- Phuket ---------------------------------------------------------
  {
    id: 'phuket-beach-getaway-5n',
    title: '5-Night Phuket Beach Getaway',
    destinationSlug: 'phuket',
    nights: 5,
    fromCity: 'Bangkok',
    fromCode: 'BKK',
    toCode: 'HKT',
    nonstop: true,
    flightClass: 'Economy',
    starRating: 4,
    price: '$489',
    wasPrice: '$612',
    dateRange: 'Oct 10 - Oct 15',
    saveBadge: 'Save 100% on your flight',
    imageIndex: 0,
    includes: ['Round-trip flights', '4-star beachfront hotel', 'Daily breakfast'],
  },
  {
    id: 'phuket-old-town-3n',
    title: '3-Night Phuket Old Town Break',
    destinationSlug: 'phuket',
    nights: 3,
    fromCity: 'Bangkok',
    fromCode: 'BKK',
    toCode: 'HKT',
    nonstop: true,
    flightClass: 'Economy',
    starRating: 3.5,
    price: '$318',
    dateRange: 'Sep 9 - Sep 12',
    imageIndex: 1,
    includes: ['Round-trip flights', 'Boutique Sino-Portuguese hotel', 'Walking food tour'],
  },
  {
    id: 'phuket-phang-nga-7n',
    title: '7-Night Phuket & Phang Nga Bay',
    destinationSlug: 'phuket',
    nights: 7,
    fromCity: 'Bangkok',
    fromCode: 'BKK',
    toCode: 'HKT',
    nonstop: true,
    flightClass: 'Economy',
    starRating: 4.5,
    price: '$742',
    wasPrice: '$890',
    dateRange: 'Oct 10 - Oct 17',
    saveBadge: 'Save 100% on your flight',
    imageIndex: 2,
    includes: [
      'Round-trip flights',
      '4.5-star resort',
      'Daily breakfast',
      'Full-day Phang Nga Bay cruise',
    ],
  },
  {
    id: 'phuket-business-4n',
    title: '4-Night Phuket in Business Class',
    destinationSlug: 'phuket',
    nights: 4,
    fromCity: 'Bangkok',
    fromCode: 'BKK',
    toCode: 'HKT',
    nonstop: true,
    flightClass: 'Business',
    starRating: 5,
    price: '$1,145',
    dateRange: 'Oct 10 - Oct 14',
    imageIndex: 0,
    includes: [
      'Round-trip business-class flights',
      '5-star beachfront resort',
      'Daily breakfast',
      'Private airport transfers',
    ],
  },

  // ---- Krabi ----------------------------------------------------------
  {
    id: 'krabi-island-hopper-6n',
    title: '6-Night Krabi Island Hopper',
    destinationSlug: 'krabi',
    nights: 6,
    fromCity: 'Bangkok',
    fromCode: 'BKK',
    toCode: 'KBV',
    nonstop: true,
    flightClass: 'Economy',
    starRating: 4,
    price: '$598',
    wasPrice: '$705',
    dateRange: 'Oct 10 - Oct 16',
    saveBadge: 'Save 100% on your flight',
    imageIndex: 0,
    includes: ['Round-trip flights', 'Railay beachfront resort', 'Full-day island tour'],
  },
  {
    id: 'krabi-railay-4n',
    title: '4-Night Railay Beach Escape',
    destinationSlug: 'krabi',
    nights: 4,
    fromCity: 'Bangkok',
    fromCode: 'BKK',
    toCode: 'KBV',
    nonstop: true,
    flightClass: 'Economy',
    starRating: 4.5,
    price: '$465',
    dateRange: 'Sep 9 - Sep 13',
    imageIndex: 1,
    includes: ['Round-trip flights', 'Cliffside resort', 'Daily breakfast', 'Longtail transfers'],
  },
  {
    id: 'krabi-phi-phi-5n',
    title: '5-Night Krabi & Phi Phi',
    destinationSlug: 'krabi',
    nights: 5,
    fromCity: 'Bangkok',
    fromCode: 'BKK',
    toCode: 'KBV',
    nonstop: false,
    flightClass: 'Economy',
    starRating: 4,
    price: '$540',
    dateRange: 'Oct 10 - Oct 15',
    imageIndex: 2,
    includes: ['Round-trip flights', 'Two-centre stay', 'Phi Phi speedboat day trip'],
  },
  {
    id: 'krabi-ao-nang-3n',
    title: '3-Night Ao Nang Short Break',
    destinationSlug: 'krabi',
    nights: 3,
    fromCity: 'Bangkok',
    fromCode: 'BKK',
    toCode: 'KBV',
    nonstop: true,
    flightClass: 'Economy',
    starRating: 3,
    price: '$298',
    wasPrice: '$349',
    dateRange: 'Sep 9 - Sep 12',
    imageIndex: 3,
    includes: ['Round-trip flights', 'Ao Nang town hotel', 'Daily breakfast'],
  },

  // ---- Koh Samui ------------------------------------------------------
  {
    id: 'koh-samui-island-life-5n',
    title: '5-Night Koh Samui Island Life',
    destinationSlug: 'koh-samui',
    nights: 5,
    fromCity: 'Bangkok',
    fromCode: 'BKK',
    toCode: 'USM',
    nonstop: true,
    flightClass: 'Economy',
    starRating: 4.5,
    price: '$545',
    wasPrice: '$668',
    dateRange: 'Oct 10 - Oct 15',
    saveBadge: 'Save 100% on your flight',
    imageIndex: 0,
    includes: ['Round-trip flights', 'Beachfront resort', 'Daily breakfast', 'Airport transfers'],
  },
  {
    id: 'koh-samui-bophut-4n',
    title: '4-Night Bophut Fisherman’s Village',
    destinationSlug: 'koh-samui',
    nights: 4,
    fromCity: 'Bangkok',
    fromCode: 'BKK',
    toCode: 'USM',
    nonstop: true,
    flightClass: 'Economy',
    starRating: 4,
    price: '$452',
    dateRange: 'Sep 9 - Sep 13',
    imageIndex: 2,
    includes: ['Round-trip flights', 'Boutique village hotel', 'Daily breakfast'],
  },
  {
    id: 'koh-samui-wellness-7n',
    title: '7-Night Koh Samui Wellness Retreat',
    destinationSlug: 'koh-samui',
    nights: 7,
    fromCity: 'Bangkok',
    fromCode: 'BKK',
    toCode: 'USM',
    nonstop: true,
    flightClass: 'Business',
    starRating: 5,
    price: '$1,380',
    wasPrice: '$1,590',
    dateRange: 'Oct 10 - Oct 17',
    saveBadge: 'Save 100% on your flight',
    imageIndex: 1,
    includes: [
      'Round-trip business-class flights',
      '5-star wellness resort',
      'All meals included',
      'Daily spa treatment',
    ],
  },
  {
    id: 'koh-samui-quick-3n',
    title: '3-Night Koh Samui Quick Escape',
    destinationSlug: 'koh-samui',
    nights: 3,
    fromCity: 'Bangkok',
    fromCode: 'BKK',
    toCode: 'USM',
    nonstop: true,
    flightClass: 'Economy',
    starRating: 3.5,
    price: '$362',
    dateRange: 'Sep 9 - Sep 12',
    imageIndex: 2,
    includes: ['Round-trip flights', 'Lamai beach hotel', 'Daily breakfast'],
  },

  // ---- Chiang Mai -----------------------------------------------------
  {
    id: 'chiang-mai-mountain-escape-4n',
    title: '4-Night Chiang Mai Mountain Escape',
    destinationSlug: 'chiang-mai',
    nights: 4,
    fromCity: 'Bangkok',
    fromCode: 'BKK',
    toCode: 'CNX',
    nonstop: true,
    flightClass: 'Economy',
    starRating: 4,
    price: '$365',
    wasPrice: '$430',
    dateRange: 'Oct 10 - Oct 14',
    saveBadge: 'Save 100% on your flight',
    imageIndex: 0,
    includes: ['Round-trip flights', 'Boutique old-town hotel', 'Half-day cooking class'],
  },
  {
    id: 'chiang-mai-old-city-3n',
    title: '3-Night Chiang Mai Old City',
    destinationSlug: 'chiang-mai',
    nights: 3,
    fromCity: 'Bangkok',
    fromCode: 'BKK',
    toCode: 'CNX',
    nonstop: true,
    flightClass: 'Economy',
    starRating: 3.5,
    price: '$289',
    dateRange: 'Sep 9 - Sep 12',
    imageIndex: 3,
    includes: ['Round-trip flights', 'Old-town guesthouse', 'Temple walking tour'],
  },
  {
    id: 'chiang-mai-doi-inthanon-6n',
    title: '6-Night Chiang Mai & Doi Inthanon',
    destinationSlug: 'chiang-mai',
    nights: 6,
    fromCity: 'Bangkok',
    fromCode: 'BKK',
    toCode: 'CNX',
    nonstop: true,
    flightClass: 'Economy',
    starRating: 4.5,
    price: '$612',
    dateRange: 'Oct 10 - Oct 16',
    imageIndex: 1,
    includes: [
      'Round-trip flights',
      'Riverside hotel',
      'Daily breakfast',
      'Doi Inthanon national park day tour',
    ],
  },
  {
    id: 'chiang-mai-golden-triangle-5n',
    title: '5-Night Chiang Mai & Golden Triangle',
    destinationSlug: 'chiang-mai',
    nights: 5,
    fromCity: 'Bangkok',
    fromCode: 'BKK',
    toCode: 'CNX',
    nonstop: false,
    flightClass: 'Economy',
    starRating: 4,
    price: '$498',
    wasPrice: '$575',
    dateRange: 'Sep 9 - Sep 14',
    imageIndex: 2,
    includes: ['Round-trip flights', 'Two-centre stay', 'White Temple day tour'],
  },

  // ---- Bangkok --------------------------------------------------------
  {
    id: 'bangkok-city-explorer-3n',
    title: '3-Night Bangkok City Explorer',
    destinationSlug: 'bangkok',
    nights: 3,
    fromCity: 'Chiang Mai',
    fromCode: 'CNX',
    toCode: 'BKK',
    nonstop: true,
    flightClass: 'Economy',
    starRating: 4,
    price: '$275',
    dateRange: 'Sep 9 - Sep 12',
    imageIndex: 0,
    includes: ['Round-trip flights', '4-star riverside hotel', 'Grand Palace tour'],
  },
  {
    id: 'bangkok-riverside-4n',
    title: '4-Night Bangkok Riverside Stay',
    destinationSlug: 'bangkok',
    nights: 4,
    fromCity: 'Phuket',
    fromCode: 'HKT',
    toCode: 'BKK',
    nonstop: true,
    flightClass: 'Economy',
    starRating: 4.5,
    price: '$398',
    wasPrice: '$465',
    dateRange: 'Oct 10 - Oct 14',
    saveBadge: 'Save 100% on your flight',
    imageIndex: 2,
    includes: ['Round-trip flights', '4.5-star riverside hotel', 'Daily breakfast'],
  },
  {
    id: 'bangkok-markets-2n',
    title: '2-Night Bangkok Markets & Street Food',
    destinationSlug: 'bangkok',
    nights: 2,
    fromCity: 'Chiang Mai',
    fromCode: 'CNX',
    toCode: 'BKK',
    nonstop: true,
    flightClass: 'Economy',
    starRating: 3,
    price: '$208',
    dateRange: 'Sep 9 - Sep 11',
    imageIndex: 1,
    includes: ['Round-trip flights', 'Sukhumvit hotel', 'Evening street-food tour'],
  },
  {
    id: 'bangkok-chinatown-3n',
    title: '3-Night Bangkok Chinatown Break',
    destinationSlug: 'bangkok',
    nights: 3,
    fromCity: 'Chiang Mai',
    fromCode: 'CNX',
    toCode: 'BKK',
    nonstop: true,
    flightClass: 'Economy',
    starRating: 3.5,
    price: '$262',
    dateRange: 'Oct 10 - Oct 13',
    imageIndex: 3,
    includes: ['Round-trip flights', 'Yaowarat boutique hotel', 'Daily breakfast'],
  },

  // ---- Chiang Rai -----------------------------------------------------
  {
    id: 'chiang-rai-golden-triangle-4n',
    title: '4-Night Chiang Rai & Golden Triangle',
    destinationSlug: 'chiang-rai',
    nights: 4,
    fromCity: 'Bangkok',
    fromCode: 'BKK',
    toCode: 'CNX',
    nonstop: false,
    flightClass: 'Economy',
    starRating: 4,
    price: '$410',
    dateRange: 'Oct 10 - Oct 14',
    imageIndex: 0,
    includes: ['Round-trip flights', 'Riverside hotel', 'White Temple day tour'],
  },
  {
    id: 'chiang-rai-white-temple-3n',
    title: '3-Night Chiang Rai White Temple',
    destinationSlug: 'chiang-rai',
    nights: 3,
    fromCity: 'Bangkok',
    fromCode: 'BKK',
    toCode: 'CNX',
    nonstop: false,
    flightClass: 'Economy',
    starRating: 3.5,
    price: '$338',
    wasPrice: '$392',
    dateRange: 'Sep 9 - Sep 12',
    saveBadge: 'Save 100% on your flight',
    imageIndex: 1,
    includes: ['Round-trip flights', 'Old-town hotel', 'White Temple and Black House tour'],
  },
];
