import type { Tour } from './types';

/**
 * Bookable tours. The badge shown on the photo is the first half of `duration`
 * ("Full day · 6 hrs" → "Full day"), derived in <TourCard>.
 */
export const tours: Tour[] = [
  {
    id: "grand-palace-wat-pho-heritage-walk",
    destinationSlug: "bangkok",
    maxGroupSize: 16,
    openMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    title: "Grand Palace & Wat Pho Heritage Walk",
    location: "Bangkok",
    duration: "Full day · 6 hrs",
    price: "$65",
    categorySlug: "temples-culture",
    durationMinutes: 360,
    startTime: "08:00",
    priceUnit: "adult",
    score: 9.6,
    reviewCount: 214,
    freeCancellation: true,
    familyFriendly: true,
    localExpertPick: true,
    hotelPickup: true,
    rating: "4.9",
    image: "/Content/wat-pho-bangkok-700-7.jpg",
    imageAlt: "Wat Pho temple, Bangkok",
    description:
      "A guided walk through Bangkok's ceremonial heart: the glittering Grand Palace, the reclining Buddha at Wat Pho, and the riverside streets between them. Small groups only, with a local guide who knows which courtyards to see before the tour buses arrive.",
    itinerary: [
      {
        time: "08:00",
        title: "Hotel pickup",
        description: "Air-conditioned van collects your group from central Bangkok hotels.",
      },
      {
        time: "09:00",
        title: "Grand Palace & Wat Phra Kaew",
        description: "Guided walk through the palace grounds and the Temple of the Emerald Buddha.",
      },
      {
        time: "11:30",
        title: "Wat Pho",
        description: "See the 46-metre reclining Buddha and the temple's original Thai massage school.",
      },
      {
        time: "13:00",
        title: "Riverside lunch",
        description: "A included lunch at a restaurant overlooking the Chao Phraya.",
      },
      {
        time: "14:30",
        title: "Return",
        description: "Drop-off back at your hotel by mid-afternoon.",
      },
    ],
  },
  {
    id: "maya-bay-phi-phi-islands-speedboat",
    destinationSlug: "krabi",
    maxGroupSize: 12,
    openMonths: [11, 12, 1, 2, 3, 4],
    title: "Maya Bay & Phi Phi Islands Speedboat",
    location: "Krabi",
    duration: "Full day · 8 hrs",
    price: "$89",
    categorySlug: "island-boat-trips",
    durationMinutes: 480,
    startTime: "07:30",
    priceUnit: "adult",
    score: 9.4,
    reviewCount: 386,
    freeCancellation: true,
    familyFriendly: true,
    localExpertPick: false,
    hotelPickup: true,
    rating: "4.8",
    image: "/Content/maya-bay-phi-phi-leh-700-2.jpg",
    imageAlt: "Maya Bay, Phi Phi Leh",
    description:
      "A full day by speedboat through the Andaman's most photographed water: the cliff-ringed cove of Maya Bay, the monkey-lined shores of Phi Phi Leh, and a snorkel stop over coral reef. Lunch and snorkel gear included.",
    itinerary: [
      {
        time: "07:30",
        title: "Pier pickup",
        description: "Transfer from your Krabi hotel to the pier for departure.",
      },
      {
        time: "08:30",
        title: "Speedboat to Phi Phi Leh",
        description: "Cruise past limestone cliffs into Maya Bay's protected cove.",
      },
      {
        time: "10:30",
        title: "Snorkeling stop",
        description: "Snorkel over coral reef at a sheltered bay with reef fish.",
      },
      {
        time: "12:30",
        title: "Lunch on Phi Phi Don",
        description: "Included buffet lunch on the main island, with free time on the beach.",
      },
      {
        time: "15:00",
        title: "Return by speedboat",
        description: "Back to the pier and transfer to your hotel by late afternoon.",
      },
    ],
  },
  {
    id: "james-bond-island-canoe-adventure",
    destinationSlug: "phuket",
    maxGroupSize: 10,
    openMonths: [11, 12, 1, 2, 3, 4],
    title: "James Bond Island Canoe Adventure",
    location: "Phang Nga",
    duration: "Full day · 7 hrs",
    price: "$74",
    categorySlug: "island-boat-trips",
    durationMinutes: 420,
    startTime: "07:00",
    priceUnit: "adult",
    score: 9.6,
    reviewCount: 158,
    freeCancellation: true,
    familyFriendly: true,
    localExpertPick: true,
    hotelPickup: true,
    rating: "4.9",
    image: "/Content/canoeing-to-cave-james-bond-island-tour-700-2.jpg",
    imageAlt: "Canoeing near James Bond Island",
    description:
      "Paddle a two-person canoe through hidden sea caves and mangrove tunnels in Phang Nga Bay, then cruise past the karst spire made famous by The Man with the Golden Gun. A quieter, more hands-on way to see the bay than the big tour boats.",
    itinerary: [
      {
        time: "07:00",
        title: "Hotel pickup",
        description: "Transfer from Phuket hotels to the pier at Phang Nga Bay.",
      },
      {
        time: "08:30",
        title: "Longtail boat to the bay",
        description: "Cruise out among the limestone karsts of Phang Nga Bay.",
      },
      {
        time: "09:30",
        title: "Canoe through sea caves",
        description: "Paddle into hidden lagoons and mangrove tunnels with a local guide.",
      },
      {
        time: "12:00",
        title: "James Bond Island & lunch",
        description: "Photo stop at Khao Phing Kan, followed by an included Thai lunch.",
      },
      {
        time: "15:30",
        title: "Return to Phuket",
        description: "Boat back to the pier and transfer to your hotel.",
      },
    ],
  },
  {
    id: "chiang-mai-ethical-elephant-sanctuary",
    destinationSlug: "chiang-mai",
    maxGroupSize: 8,
    openMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    title: "Chiang Mai Ethical Elephant Sanctuary",
    location: "Chiang Mai",
    duration: "Full day · 6 hrs",
    price: "$58",
    categorySlug: "wildlife-nature",
    durationMinutes: 360,
    startTime: "08:30",
    priceUnit: "adult",
    score: 10,
    reviewCount: 97,
    freeCancellation: true,
    familyFriendly: true,
    localExpertPick: true,
    hotelPickup: true,
    rating: "5.0",
    image: "/Content/elephant-nature-park-700-6.jpg",
    imageAlt: "Elephant Nature Park, Chiang Mai",
    description:
      "Spend a day at a no-riding, no-chains sanctuary in the hills outside Chiang Mai, feeding and walking alongside rescued elephants in their own river valley. Small groups, and every visit funds the sanctuary's rescue program.",
    itinerary: [
      {
        time: "08:00",
        title: "Hotel pickup",
        description: "Van transfer from Chiang Mai's old town into the hills.",
      },
      {
        time: "09:00",
        title: "Meet the herd",
        description: "Introduction to the sanctuary's rescued elephants and their keepers.",
      },
      {
        time: "10:00",
        title: "Feeding & walking",
        description: "Prepare food and walk alongside the elephants through the valley.",
      },
      {
        time: "12:00",
        title: "Riverside lunch",
        description: "Included vegetarian lunch overlooking the river.",
      },
      {
        time: "13:30",
        title: "Mud bath & river bathing",
        description: "Join the elephants for a mud wallow and a splash in the river.",
      },
      {
        time: "15:30",
        title: "Return",
        description: "Transfer back to your Chiang Mai hotel.",
      },
    ],
  },
  {
    id: "ayutthaya-ancient-capital-day-trip",
    destinationSlug: "ayutthaya",
    maxGroupSize: 14,
    openMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    title: "Ayutthaya Ancient Capital Day Trip",
    location: "Ayutthaya",
    duration: "Full day · 6 hrs",
    price: "$52",
    categorySlug: "temples-culture",
    durationMinutes: 360,
    startTime: "07:30",
    priceUnit: "adult",
    score: 9.2,
    reviewCount: 131,
    freeCancellation: true,
    familyFriendly: true,
    localExpertPick: false,
    hotelPickup: true,
    rating: "4.7",
    image: "/Content/ayutthaya-chao-sam-phraya-national-museum-700-2.jpg",
    imageAlt: "Ayutthaya historic ruins",
    description:
      "A day trip north from Bangkok to Siam's former capital, now a quiet field of brick temple ruins and headless Buddha statues. Includes a river cruise back into the city as the sun sets over the water.",
    itinerary: [
      {
        time: "08:00",
        title: "Hotel pickup",
        description: "Van transfer north out of Bangkok to Ayutthaya.",
      },
      {
        time: "09:30",
        title: "Wat Mahathat",
        description: "See the famous Buddha head entwined in tree roots.",
      },
      {
        time: "11:00",
        title: "Wat Chaiwatthanaram",
        description: "Explore the riverside temple built in the style of Angkor Wat.",
      },
      {
        time: "12:30",
        title: "Lunch",
        description: "Included Thai lunch near the historic park.",
      },
      {
        time: "14:00",
        title: "Chao Sam Phraya Museum",
        description: "A short visit to see treasures recovered from the ruined temples.",
      },
      {
        time: "16:00",
        title: "River cruise back to Bangkok",
        description: "Return by boat along the Chao Phraya as the sun sets.",
      },
    ],
  },
  {
    id: "river-kwai-kanchanaburi-explorer",
    destinationSlug: "kanchanaburi",
    maxGroupSize: 12,
    openMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    title: "River Kwai & Kanchanaburi Explorer",
    location: "Kanchanaburi",
    duration: "Full day · 7 hrs",
    price: "$60",
    categorySlug: "outdoor-adventure",
    durationMinutes: 420,
    startTime: "07:00",
    priceUnit: "adult",
    score: 9.0,
    reviewCount: 88,
    freeCancellation: true,
    familyFriendly: true,
    localExpertPick: false,
    hotelPickup: true,
    rating: "4.6",
    image: "/Content/kanchanaburi-bridge-over-the-river-kwai-700-2.jpg",
    imageAlt: "Bridge over the River Kwai",
    description:
      "A full day pairing the sobering wartime history of the bridge over the River Kwai with the turquoise, seven-tiered pools of Erawan National Park — two hours from Bangkok but a world apart.",
    itinerary: [
      {
        time: "07:00",
        title: "Hotel pickup",
        description: "Van transfer west from Bangkok to Kanchanaburi.",
      },
      {
        time: "09:30",
        title: "Bridge over the River Kwai",
        description: "Walk the bridge and visit the nearby war cemetery and museum.",
      },
      {
        time: "11:00",
        title: "Erawan National Park",
        description: "Hike the seven-tiered waterfall trail and swim in the pools.",
      },
      {
        time: "13:00",
        title: "Lunch",
        description: "Included riverside lunch near the park.",
      },
      {
        time: "15:00",
        title: "Return to Bangkok",
        description: "Drive back, arriving in the early evening.",
      },
    ],
  },
  {
    id: "golden-triangle-white-temple-tour",
    destinationSlug: "chiang-rai",
    maxGroupSize: 10,
    openMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    title: "Golden Triangle & White Temple Tour",
    location: "Chiang Rai",
    duration: "2 days · 1 night",
    price: "$145",
    categorySlug: "temples-culture",
    durationMinutes: 1740,
    startTime: "08:00",
    priceUnit: "traveler",
    score: 9.4,
    reviewCount: 64,
    freeCancellation: false,
    familyFriendly: false,
    localExpertPick: true,
    hotelPickup: true,
    rating: "4.8",
    image: "/Content/thailand-golden-triangle-700-1.jpg",
    imageAlt: "Golden Triangle, Chiang Rai",
    description:
      "An overnight trip from Chiang Mai through Chiang Rai's contemporary temples — the dazzling White Temple and the stark Black House — out to the Golden Triangle where Thailand, Laos and Myanmar meet along the Mekong.",
    itinerary: [
      {
        time: "Day 1, 07:00",
        title: "Depart Chiang Mai",
        description: "Van transfer north to Chiang Rai.",
      },
      {
        time: "Day 1, 10:00",
        title: "White Temple (Wat Rong Khun)",
        description: "Explore the dazzling contemporary temple complex.",
      },
      {
        time: "Day 1, 13:00",
        title: "Black House (Baan Dam)",
        description: "Visit the dark counterpart museum built by the same artist.",
      },
      {
        time: "Day 1, evening",
        title: "Overnight in Chiang Rai",
        description: "Check in to a hotel in town; dinner on your own.",
      },
      {
        time: "Day 2, 08:00",
        title: "Golden Triangle",
        description: "See where Thailand, Laos, and Myanmar meet along the Mekong.",
      },
      {
        time: "Day 2, 14:00",
        title: "Return to Chiang Mai",
        description: "Afternoon drive back, arriving in the early evening.",
      },
    ],
  },
  {
    id: "koh-samui-island-escape",
    destinationSlug: "koh-samui",
    maxGroupSize: 8,
    openMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    title: "Koh Samui Island Escape",
    location: "Koh Samui",
    duration: "3 days · 2 nights",
    price: "$210",
    categorySlug: "island-boat-trips",
    durationMinutes: 2880,
    startTime: "09:00",
    priceUnit: "traveler",
    score: 9.6,
    reviewCount: 52,
    freeCancellation: false,
    familyFriendly: true,
    localExpertPick: false,
    hotelPickup: false,
    rating: "4.9",
    image: "/Content/thailand-koh-samui-700-2.jpg",
    imageAlt: "The Big Buddha at Wat Phra Yai, Koh Samui",
    description:
      "Three unhurried days on Koh Samui: palm-lined coastline, the low-key charm of Bophut's Fisherman's Village, and enough free time to actually feel like a vacation instead of a checklist.",
    itinerary: [
      {
        time: "Day 1",
        title: "Arrival & Fisherman's Village",
        description: "Settle in, then explore Bophut's restored wooden shophouses at sunset.",
      },
      {
        time: "Day 2",
        title: "Island coastline & viewpoints",
        description: "Guided half-day around the island's beaches and coastal viewpoints; afternoon free.",
      },
      {
        time: "Day 3",
        title: "Free morning & departure",
        description: "A free morning to swim or relax before transfer to the airport or pier.",
      },
    ],
  },
  {
    id: "bangkok-street-food-night-walk",
    destinationSlug: "bangkok",
    categorySlug: "food-markets",
    maxGroupSize: 10,
    openMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    title: "Bangkok Street Food Night Walk",
    location: "Bangkok",
    duration: "Evening · 4 hrs",
    durationMinutes: 240,
    startTime: "17:30",
    price: "$46",
    priceUnit: "adult",
    score: 9.8,
    reviewCount: 176,
    freeCancellation: true,
    familyFriendly: true,
    localExpertPick: true,
    hotelPickup: false,
    rating: "4.9",
    image: "/Content/chinatown-bangkok-yaowarat-700-1.jpg",
    imageAlt: "Yaowarat Road, Bangkok's Chinatown, at night",
    description:
      "Eight tasting stops through Yaowarat and the lanes behind it, walked at the pace the street actually moves. Your guide orders in Thai, explains what is in front of you, and knows which stalls open late and which sell out by nine.",
    itinerary: [
      { time: "17:30", title: "Meet at Wat Traimit", description: "Group meets by the Golden Buddha at the entrance to Chinatown." },
      { time: "18:00", title: "Yaowarat Road", description: "Grilled river prawns, oyster omelette and guay jub noodle soup." },
      { time: "19:30", title: "Soi Texas lanes", description: "Charcoal satay, pork toast and a stop for fresh pomegranate juice." },
      { time: "21:00", title: "Dessert and finish", description: "Mango sticky rice, then directions to the nearest MRT station." },
    ],
  },
  {
    id: "maeklong-damnoen-saduak-markets",
    destinationSlug: "bangkok",
    categorySlug: "food-markets",
    maxGroupSize: 14,
    openMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    title: "Maeklong Railway & Floating Market Morning",
    location: "Samut Songkhram",
    duration: "Half day · 5 hrs",
    durationMinutes: 300,
    startTime: "06:30",
    price: "$44",
    priceUnit: "adult",
    score: 9.0,
    reviewCount: 203,
    freeCancellation: true,
    familyFriendly: true,
    localExpertPick: false,
    hotelPickup: true,
    rating: "4.6",
    image: "/Content/maeklong-railway-market-700-3.jpg",
    imageAlt: "Stallholders folding awnings as a train passes Maeklong market",
    description:
      "An early start for the two markets outside Bangkok that are worth the alarm: the railway market that packs itself away as the train arrives, and Damnoen Saduak, reached by longtail through the canals rather than the coach park.",
    itinerary: [
      { time: "06:30", title: "Hotel pickup", description: "Air-conditioned van from central Bangkok hotels." },
      { time: "08:15", title: "Maeklong railway market", description: "Watch the awnings fold back as the 08:30 service passes through." },
      { time: "09:45", title: "Damnoen Saduak by longtail", description: "Enter the floating market from the canal side, away from the main jetty." },
      { time: "11:30", title: "Return", description: "Back in central Bangkok by late morning." },
    ],
  },
  {
    id: "chao-phraya-sunset-dinner-cruise",
    destinationSlug: "bangkok",
    categorySlug: "evening-cruises",
    maxGroupSize: 20,
    openMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    title: "Chao Phraya Sunset Dinner Cruise",
    location: "Bangkok",
    duration: "Evening · 3 hrs",
    durationMinutes: 180,
    startTime: "18:00",
    price: "$52",
    priceUnit: "adult",
    score: 9.2,
    reviewCount: 264,
    freeCancellation: true,
    familyFriendly: true,
    localExpertPick: false,
    hotelPickup: false,
    rating: "4.7",
    image: "/Content/wat-arun-thai-eiffel-tower-700-1.jpg",
    imageAlt: "Wat Arun lit up above the Chao Phraya river",
    description:
      "A three-hour sailing from Asiatique pier past Wat Arun, the Grand Palace and the Rama VIII bridge, with dinner served on the open upper deck as the light goes.",
    itinerary: [
      { time: "18:00", title: "Board at Asiatique", description: "Check in at the pier; seating is allocated on the open upper deck." },
      { time: "18:45", title: "Cast off", description: "Head upriver as the sun drops behind the Thonburi bank." },
      { time: "19:30", title: "Dinner service", description: "Thai and international buffet with a live acoustic set." },
      { time: "21:00", title: "Return to pier", description: "Back at Asiatique, a short walk from the riverfront market." },
    ],
  },
  {
    id: "phuket-old-town-food-heritage",
    destinationSlug: "phuket",
    categorySlug: "food-markets",
    maxGroupSize: 10,
    openMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    title: "Phuket Old Town Food & Heritage Walk",
    location: "Phuket",
    duration: "Half day · 4 hrs",
    durationMinutes: 240,
    startTime: "16:00",
    price: "$41",
    priceUnit: "adult",
    score: 9.4,
    reviewCount: 119,
    freeCancellation: true,
    familyFriendly: true,
    localExpertPick: true,
    hotelPickup: false,
    rating: "4.8",
    image: "/Content/phuket-old-town-700-2.jpg",
    imageAlt: "Sino-Portuguese shophouses in Phuket Old Town",
    description:
      "Phuket's Sino-Portuguese quarter on foot, stopping for Hokkien noodles, moo hong and kanom jeen along the way. The food explains the architecture — both arrived with the tin-mining families who built these streets.",
    itinerary: [
      { time: "16:00", title: "Meet on Thalang Road", description: "Group meets outside the old Standard Chartered building." },
      { time: "16:30", title: "Shophouse lanes", description: "Hokkien mee and a stop at a hundred-year-old coffee shop." },
      { time: "18:00", title: "Evening market", description: "Moo hong, roti and southern-style curries as the stalls open." },
      { time: "20:00", title: "Finish", description: "End on Soi Romanee, with recommendations for the rest of the evening." },
    ],
  },
  {
    id: "phang-nga-bay-sea-cave-kayak",
    destinationSlug: "phuket",
    categorySlug: "island-boat-trips",
    maxGroupSize: 12,
    openMonths: [1, 2, 3, 4, 11, 12],
    title: "Phang Nga Bay Sea Cave Kayaking",
    location: "Phang Nga",
    duration: "Full day · 8 hrs",
    durationMinutes: 480,
    startTime: "07:00",
    price: "$82",
    priceUnit: "adult",
    score: 9.6,
    reviewCount: 141,
    freeCancellation: true,
    familyFriendly: true,
    localExpertPick: true,
    hotelPickup: true,
    rating: "4.9",
    image: "/Content/canoeing-to-cave-james-bond-island-tour-700-2.jpg",
    imageAlt: "A canoe entering a sea cave in Phang Nga Bay",
    description:
      "Paddling into the hongs — the collapsed cave chambers hidden inside Phang Nga's limestone islands — with a guide per canoe. Timed around the tide, so the low entrances are actually passable.",
    itinerary: [
      { time: "07:00", title: "Hotel pickup", description: "Collection from Phuket hotels, then a short transfer to the pier." },
      { time: "09:00", title: "Panak and Hong islands", description: "Two guided cave paddles into the interior lagoons." },
      { time: "12:30", title: "Lunch on board", description: "Southern Thai lunch served as the boat repositions." },
      { time: "14:00", title: "Free paddle", description: "An hour to explore a quieter bay at your own pace." },
      { time: "16:30", title: "Return", description: "Back at your hotel by early evening." },
    ],
  },
  {
    id: "khao-sok-jungle-lake-overnight",
    destinationSlug: "khao-yai-national-park",
    categorySlug: "wildlife-nature",
    maxGroupSize: 8,
    openMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    title: "Khao Sok Rainforest & Lake Overnight",
    location: "Surat Thani",
    duration: "2 days · 1 night",
    durationMinutes: 1800,
    startTime: "07:30",
    price: "$168",
    priceUnit: "traveler",
    score: 9.8,
    reviewCount: 73,
    freeCancellation: false,
    familyFriendly: false,
    localExpertPick: true,
    hotelPickup: true,
    rating: "4.9",
    image: "/Content/khao-sok-national-park-700-1.jpg",
    imageAlt: "Limestone cliffs above Cheow Lan lake, Khao Sok",
    description:
      "A night in a floating raft house on Cheow Lan lake, with a dawn longtail out to look for gibbons and hornbills before the day boats arrive. Rainforest here is older than the Amazon.",
    itinerary: [
      { time: "07:30", title: "Pickup", description: "Collection from Surat Thani or Khao Lak hotels." },
      { time: "11:00", title: "Longtail across the lake", description: "An hour on the water to the raft houses beneath the karsts." },
      { time: "15:00", title: "Jungle walk", description: "Guided trail to a cave system, then swimming from the raft." },
      { time: "06:00", title: "Dawn wildlife cruise", description: "Early longtail to the far arms of the lake for gibbons and hornbills." },
      { time: "13:00", title: "Return", description: "Back across the lake and on to your onward hotel." },
    ],
  },
  {
    id: "chiang-mai-cooking-class-market",
    destinationSlug: "chiang-mai",
    categorySlug: "workshops-classes",
    maxGroupSize: 10,
    openMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    title: "Chiang Mai Cooking Class & Market Tour",
    location: "Chiang Mai",
    duration: "Half day · 5 hrs",
    durationMinutes: 300,
    startTime: "09:00",
    price: "$38",
    priceUnit: "adult",
    score: 9.6,
    reviewCount: 288,
    freeCancellation: true,
    familyFriendly: true,
    localExpertPick: false,
    hotelPickup: true,
    rating: "4.8",
    image: "/Content/chiang-mai-cooking-class-700-3.jpg",
    imageAlt: "A northern Thai cooking class in progress",
    description:
      "Shop the market first, cook five dishes after — curry paste pounded by hand, khao soi, and whatever is good that morning. You eat what you make and leave with the recipes.",
    itinerary: [
      { time: "09:00", title: "Market visit", description: "Walk a local market with your teacher, choosing herbs and produce." },
      { time: "10:30", title: "Curry paste", description: "Pound your own paste in a granite mortar — the part most classes skip." },
      { time: "11:30", title: "Cook five dishes", description: "Khao soi, a stir fry, a soup, a salad and a dessert." },
      { time: "13:30", title: "Eat and finish", description: "Sit down to what you cooked, then drop-off back in the old city." },
    ],
  },
  {
    id: "doi-inthanon-summit-waterfalls",
    destinationSlug: "chiang-mai",
    categorySlug: "outdoor-adventure",
    maxGroupSize: 12,
    openMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    title: "Doi Inthanon Summit & Waterfalls",
    location: "Chiang Mai",
    duration: "Full day · 9 hrs",
    durationMinutes: 540,
    startTime: "07:00",
    price: "$56",
    priceUnit: "adult",
    score: 9.2,
    reviewCount: 167,
    freeCancellation: true,
    familyFriendly: true,
    localExpertPick: false,
    hotelPickup: true,
    rating: "4.7",
    image: "/Content/chiangmai-doi-national-park-700-1.jpg",
    imageAlt: "Gardens and pagodas near the summit of Doi Inthanon",
    description:
      "Thailand's highest point, the twin royal pagodas below it, and the Wachirathan falls on the way back down. Bring a layer — it is fifteen degrees cooler up there than in the city.",
    itinerary: [
      { time: "07:00", title: "Hotel pickup", description: "Collection from Chiang Mai hotels." },
      { time: "09:30", title: "Wachirathan waterfall", description: "Stop at the eighty-metre falls on the park road." },
      { time: "11:00", title: "Summit and pagodas", description: "The highest point in Thailand, then the twin royal pagodas and their gardens." },
      { time: "13:00", title: "Karen village lunch", description: "Lunch at a hill-tribe village, with time to walk the terraced fields." },
      { time: "16:00", title: "Return", description: "Back in Chiang Mai by early evening." },
    ],
  },
  {
    id: "chiang-mai-thai-massage-workshop",
    destinationSlug: "chiang-mai",
    categorySlug: "wellness-spa",
    maxGroupSize: 8,
    openMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    title: "Northern Thai Massage Half-Day Workshop",
    location: "Chiang Mai",
    duration: "Half day · 4 hrs",
    durationMinutes: 240,
    startTime: "13:00",
    price: "$49",
    priceUnit: "adult",
    score: 9.4,
    reviewCount: 61,
    freeCancellation: true,
    familyFriendly: false,
    localExpertPick: true,
    hotelPickup: false,
    rating: "4.8",
    image: "/Content/10-Best-Attractions-Thailand-Wat-Phra-Singh.jpg",
    imageAlt: "Wat Phra Singh in Chiang Mai's old city",
    description:
      "A working introduction to nuad boran with a teacher from the Wat Pho lineage: the pressure lines, the stretches, and enough of a routine to keep using on each other afterwards.",
    itinerary: [
      { time: "13:00", title: "Theory and warm-up", description: "The sen energy lines and how northern practice differs from Bangkok's." },
      { time: "14:00", title: "Practice in pairs", description: "Work through a back, shoulder and leg sequence with correction." },
      { time: "16:00", title: "Full routine", description: "Run the sequence end to end, then swap." },
      { time: "17:00", title: "Finish", description: "Tea, a printed sequence card, and directions back to the old city." },
    ],
  },
  {
    id: "krabi-four-islands-longtail",
    destinationSlug: "krabi",
    categorySlug: "island-boat-trips",
    maxGroupSize: 16,
    openMonths: [1, 2, 3, 4, 11, 12],
    title: "Krabi Four Islands Longtail Trip",
    location: "Krabi",
    duration: "Full day · 7 hrs",
    durationMinutes: 420,
    startTime: "08:30",
    price: "$38",
    priceUnit: "adult",
    score: 8.8,
    reviewCount: 412,
    freeCancellation: true,
    familyFriendly: true,
    localExpertPick: false,
    hotelPickup: true,
    rating: "4.5",
    image: "/Content/krabi-Railay-700-2.jpg",
    imageAlt: "Longtail boats on the beach at Railay, Krabi",
    description:
      "Phra Nang cave beach, Chicken Island, Tup and Mor — the classic Krabi run by longtail rather than speedboat, which means a slower day and quieter stops. Snorkelling gear and lunch on the sand included.",
    itinerary: [
      { time: "08:30", title: "Ao Nang pier", description: "Board a longtail from the beach; life jackets and gear issued." },
      { time: "09:30", title: "Phra Nang cave beach", description: "Swim beneath the limestone overhang below Railay." },
      { time: "11:00", title: "Tup and Mor islands", description: "Walk the sandbar between the two at low tide." },
      { time: "12:30", title: "Lunch on Poda", description: "Thai lunch on the beach, then time to snorkel the reef edge." },
      { time: "15:30", title: "Return", description: "Back at Ao Nang mid-afternoon." },
    ],
  },
  {
    id: "koh-samui-sunset-catamaran",
    destinationSlug: "koh-samui",
    categorySlug: "evening-cruises",
    maxGroupSize: 18,
    openMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 12],
    title: "Koh Samui Sunset Catamaran Sail",
    location: "Koh Samui",
    duration: "Evening · 3 hrs",
    durationMinutes: 180,
    startTime: "16:30",
    price: "$68",
    priceUnit: "adult",
    score: 9.6,
    reviewCount: 94,
    freeCancellation: true,
    familyFriendly: true,
    localExpertPick: true,
    hotelPickup: true,
    rating: "4.9",
    image: "/Content/thailand-koh-samui-700-4.jpg",
    imageAlt: "The coastline of Koh Samui at golden hour",
    description:
      "Out of Bang Rak under sail, around the Five Islands and back in the dark. Snorkelling stop before the light goes, then dinner on deck as the sun drops behind Ang Thong.",
    itinerary: [
      { time: "16:30", title: "Board at Bang Rak", description: "Short tender out to the catamaran; safety briefing on board." },
      { time: "17:15", title: "Sail to the Five Islands", description: "Under sail along the north-west coast, with time in the water." },
      { time: "18:30", title: "Sunset and dinner", description: "Grilled seafood and salads served as the light goes." },
      { time: "19:30", title: "Return", description: "Back at Bang Rak pier, with transfers to your hotel." },
    ],
  },
  {
    id: "sukhothai-historical-park-cycle",
    destinationSlug: "sukhothai",
    categorySlug: "temples-culture",
    maxGroupSize: 10,
    openMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    title: "Sukhothai Historical Park by Bicycle",
    location: "Sukhothai",
    duration: "Half day · 5 hrs",
    durationMinutes: 300,
    startTime: "07:30",
    price: "$43",
    priceUnit: "adult",
    score: 9.4,
    reviewCount: 58,
    freeCancellation: true,
    familyFriendly: true,
    localExpertPick: true,
    hotelPickup: true,
    rating: "4.8",
    image: "/Content/10-Best-Attractions-Thailand-Sukhothai-Wat.jpg",
    imageAlt: "A seated Buddha among the ruins of Sukhothai",
    description:
      "The first Thai capital, ridden rather than walked — the park is flat, shaded and far larger than it looks. An early start puts you at Wat Mahathat before the heat and the coaches.",
    itinerary: [
      { time: "07:30", title: "Bikes and briefing", description: "Collect bicycles at the park gate; helmets and water provided." },
      { time: "08:00", title: "Central zone", description: "Wat Mahathat, Wat Si Sawai and the royal palace mounds." },
      { time: "10:00", title: "Northern zone", description: "Ride out to Wat Si Chum and its eleven-metre seated Buddha." },
      { time: "11:30", title: "Finish", description: "Return the bikes; drop-off at your hotel or the bus station." },
    ],
  },
];
