import type { Tour } from './types';

/**
 * Bookable tours. The badge shown on the photo is the first half of `duration`
 * ("Full day · 6 hrs" → "Full day"), derived in <TourCard>.
 */
export const tours: Tour[] = [
  {
    id: "grand-palace-wat-pho-heritage-walk",
    destinationSlug: "bangkok",
    maxGroupSize: 16,
    openMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    title: "Grand Palace & Wat Pho Heritage Walk",
    location: "Bangkok",
    duration: "Full day · 6 hrs",
    price: "$65",
    rating: "4.9",
    image: "/Content/wat-pho-bangkok-700-7.jpg",
    imageAlt: "Wat Pho temple, Bangkok",
  },
  {
    id: "maya-bay-phi-phi-islands-speedboat",
    destinationSlug: "krabi",
    maxGroupSize: 12,
    openMonths: [11, 12, 1, 2, 3, 4],
    title: "Maya Bay & Phi Phi Islands Speedboat",
    location: "Krabi",
    duration: "Full day · 8 hrs",
    price: "$89",
    rating: "4.8",
    image: "/Content/maya-bay-phi-phi-leh-700-2.jpg",
    imageAlt: "Maya Bay, Phi Phi Leh",
  },
  {
    id: "james-bond-island-canoe-adventure",
    destinationSlug: "phuket",
    maxGroupSize: 10,
    openMonths: [11, 12, 1, 2, 3, 4],
    title: "James Bond Island Canoe Adventure",
    location: "Phang Nga",
    duration: "Full day · 7 hrs",
    price: "$74",
    rating: "4.9",
    image: "/Content/canoeing-to-cave-james-bond-island-tour-700-2.jpg",
    imageAlt: "Canoeing near James Bond Island",
  },
  {
    id: "chiang-mai-ethical-elephant-sanctuary",
    destinationSlug: "chiang-mai",
    maxGroupSize: 8,
    openMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    title: "Chiang Mai Ethical Elephant Sanctuary",
    location: "Chiang Mai",
    duration: "Full day · 6 hrs",
    price: "$58",
    rating: "5.0",
    image: "/Content/elephant-nature-park-700-6.jpg",
    imageAlt: "Elephant Nature Park, Chiang Mai",
  },
  {
    id: "ayutthaya-ancient-capital-day-trip",
    destinationSlug: "ayutthaya",
    maxGroupSize: 14,
    openMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    title: "Ayutthaya Ancient Capital Day Trip",
    location: "Ayutthaya",
    duration: "Full day · 6 hrs",
    price: "$52",
    rating: "4.7",
    image: "/Content/ayutthaya-chao-sam-phraya-national-museum-700-2.jpg",
    imageAlt: "Ayutthaya historic ruins",
  },
  {
    id: "river-kwai-kanchanaburi-explorer",
    destinationSlug: "kanchanaburi",
    maxGroupSize: 12,
    openMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    title: "River Kwai & Kanchanaburi Explorer",
    location: "Kanchanaburi",
    duration: "Full day · 7 hrs",
    price: "$60",
    rating: "4.6",
    image: "/Content/kanchanaburi-bridge-over-the-river-kwai-700-2.jpg",
    imageAlt: "Bridge over the River Kwai",
  },
  {
    id: "golden-triangle-white-temple-tour",
    destinationSlug: "chiang-rai",
    maxGroupSize: 10,
    openMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    title: "Golden Triangle & White Temple Tour",
    location: "Chiang Rai",
    duration: "2 days · 1 night",
    price: "$145",
    rating: "4.8",
    image: "/Content/thailand-golden-triangle-700-1.jpg",
    imageAlt: "Golden Triangle, Chiang Rai",
  },
  {
    id: "koh-samui-island-escape",
    destinationSlug: "koh-samui",
    maxGroupSize: 8,
    openMonths: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    title: "Koh Samui Island Escape",
    location: "Koh Samui",
    duration: "3 days · 2 nights",
    price: "$210",
    rating: "4.9",
    image: "/Content/thailand-koh-samui-700-2.jpg",
    imageAlt: "Koh Samui coastline",
  },
];
